# -*- coding: utf-8 -*-
"""Pijar_Mahir_Online_Retail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQ0WB1Jd4cwCxRPwFQDn8oawJSjKDF20
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/File_Data /online_retail_II.csv')

# Melihat 5 Data Teratas
df.head()

# Melihat Type Data 
df.info()

# Mencari Data Duplikat
df.duplicated().sum()

# Menghapus Data Duplikat
df = df.drop_duplicates()
df.duplicated().sum()

#Melihat Banyaknya keberagaman data 
df.select_dtypes(include='object').nunique()

df.select_dtypes(exclude='object').nunique()

# Mengganti type data
df["date"] = pd.to_datetime(df["InvoiceDate"])
df["Customer ID"] = df["Customer ID"].astype("str")

# Penambahan kolom date
df.head()

# Penambahan kolom date
df.info()

# Mengecheck banyaknya nilai null
df.isnull().sum()

# Membuang baris null
df_final = df[df.Description.notnull()]
df_final

# Statistic descriptive
df_final.describe()

# Melihat outlier
df_final[["Price"]].boxplot()

# Melihat outlier
df_final[["Quantity"]].boxplot()

# remove outllers
def remove_outlier(df_in,col_name):
  q1 = df_in[col_name].quantile(0.25)
  q3 = df_in[col_name].quantile(0.75)
  iqr = q3-q1 #Interquartile range
  fence_low = q1 - 1.5*iqr
  fence_high = q3 + 1.5*iqr
  df_out = df_in.loc[(df_in[col_name] > fence_low)& (df_in[col_name] < fence_high)]
  return df_out

df_P_out = remove_outlier(df_final, "Price")
remove_outlier(df_final, "Price")[["Price"]].boxplot()
remove_outlier(df_final, "Price")[["Price"]].describe()

df_Q_out = remove_outlier(df_final, "Quantity")
remove_outlier(df_final, "Quantity")[["Quantity"]].boxplot()
remove_outlier(df_final, "Quantity")[["Quantity"]].describe()

# Melihat kecocokan data
corr = df_final.corr()
sns.heatmap(corr, cmap="Blues", annot=True)

# Banyaknya pembagian data use case country
sns.countplot(y='Country', data=df)
plt.show()

# Banyaknya item (Description)
df['Description'].value_counts()

# Plot
x = df_Q_out["date"]
y = df_Q_out["Quantity"]
plt.figure(figsize=(20,7))

plt.plot(x, y)

plt.xlabel('time (datetime)')
plt.ylabel('Quantity')
plt.title('Kenaikan Quantity')
plt.grid(True)
plt.show

# Plot
x = df_P_out["date"]
y = df_P_out["Price"]
plt.figure(figsize=(20,7))

plt.plot(x, y)

plt.xlabel('time (datetime)')
plt.ylabel('Price')
plt.title('Kenaikan Price')
plt.grid(True)
plt.show